<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jk</string>
	</array>
	<key>name</key>
	<string>Jack</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(--)(?!\[\[).*$\n?</string>
			<key>name</key>
			<string>comment.line.jack</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>punctuation.terminator.statement</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(assert|return|loop|if|else)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|nil)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?[1-9][0-9]*</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.execute</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[a-zA-Z_][a-zA-Z0-9_]*(!)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>match</key>
			<string>{ *((?:[a-zA-Z_][a-zA-Z0-9_]* *)+)\|</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>:=</string>
			<key>name</key>
			<string>keyword.declaration</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:=</string>
			<key>name</key>
			<string>keyword.assignment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!</string>
			<key>name</key>
			<string>storage.type.execute</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|\/|%|&lt;|&gt;|~=|==|&lt;=|&gt;=</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>meta.brace.square</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&lt;|\&gt;</string>
			<key>name</key>
			<string>meta.brace.angle</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jack</string>
	<key>uuid</key>
	<string>79497c46-d13d-4b50-8389-c4c8cac6f3a5</string>
</dict>
</plist>
